### ISSUE TITLE
Fit a regression to predict some future values.

### ISSUE THREAD

**Issue by anirbanrkmission** [anirbanrkmission/stock_market_analysis#10]
Using scikit-learn, tensorflow, kerus and scipy we will fit a model, which will be able to make some better prediction on purchasing.

**Comment by anirbanrkmission** [comment]
MNIST.ipynb regarding that issues.

**Comment by anirbanrkmission** [comment]
Now, we'll try ANN regarding this issues.

@approjecthub

**Comment by approjecthub** [comment]
I am trying to do that using sequential model of keras! But I am getting some error while fitting it. I have uploaded my code(untitled2.ipynb) with dataset(sp500.csv).
please have a look @anirbanrkmission

**Comment by approjecthub** [comment]
I successfully fitted data on sequential model. But it is giving no better result than linear regression. I uploaded the file today,please check that

**Comment by anirbanrkmission** [comment]
I'll check it soon.
