### ISSUE TITLE
Hurst Exponent implementation for predictability checking.

### ISSUE THREAD

**Issue by anirbanrkmission** [anirbanrkmission/stock_market_analysis#13]
Post the code with any daywise data set on which the hurst exponent is implemented.

**Comment by approjecthub** [comment]
I have calculated the value of hurst exponent for **wipro daywise data**.
Please go through this  [link:](https://github.com/approjecthub/stock_market_analysis/blob/stock_market-patch-1/hurst_exponent_on_wipro_daywise.ipynb)
