### ISSUE TITLE
Extract suitable features.

### ISSUE THREAD

**Issue by anirbanrkmission** [anirbanrkmission/stock_market_analysis#9]
Extract those features which will differentiate between two different share.

**Comment by anirbanrkmission** [comment]
@approjecthub I am very confused with this particular issue and it is also the back-born of our project. Please @approjecthub and @sanchari2018 please help me on this issue.

**Comment by approjecthub** [comment]
Ok, I will share my thoughts after completing feature extraction portion on the google crash course

**Comment by approjecthub** [comment]
https://classroom.udacity.com/courses/ud501 go through this course @anirbanrkmission, you may find some important details!

**Comment by anirbanrkmission** [comment]
**Running time average** and **total turn over**.
